sudo: false
language: java
jdk: oraclejdk8
env:
- DISPLAY=:99.0
cache:
directories:
- $HOME/.m2
install: true
before_script:
- sh -e /etc/init.d/xvfb start
script:
- export
- mvn clean verify
- mvn verify -Pit-tomcat
